apiVersion: v1
kind: Service
metadata:
  name: my-backend-service
spec:
  selector:
    app: my-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: h2
      protocol: TCP
      port: 9092
      targetPort: 9092
  type: LoadBalancer
  externalTrafficPolicy: Cluster



